server:
  port: 8000

spring:
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: EMBEDDED
      encoding: UTF-8
      data-locations: >
        classpath:/data/teams.sql,
        classpath:/data/members.sql,
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _audit
            store_data_at_delete: true
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_nationalized_character_data: true
        globally_quoted_identifiers: false
        format_sql: true
